# Configuración esencial para Godot 4.3
env = SConscript("godot-cpp/SConstruct")

# Nombre explícito de la librería
lib_name = "libwfc"

# Fuentes
src = Glob("src/*.cpp")

# Build para Windows/Linux
shared_lib = env.SharedLibrary(
    target = f"../addons/wfc/bin/{env['platform']}/{lib_name}", 
    source = src
)

Default(shared_lib)