name: Build and Package WFC Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform: [windows, linux, macos]
        include:
          - platform: windows
            runner: windows-latest
          - platform: linux
            runner: ubuntu-latest
          - platform: macos
            runner: macos-latest

    runs-on: ${{ matrix.runner }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          python -m pip install scons
          if [[ "${{ matrix.platform }}" == "windows" ]]; then
            choco install make
          fi

      - name: Build for ${{ matrix.platform }}
        run: |
          cd GDExtension
          scons platform=${{ matrix.platform }} target=template_release -j4
          mkdir -p ../addons/wfc/bin/${{ matrix.platform }}
          cp libwfc.* ../addons/wfc/bin/${{ matrix.platform }}/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: addons/wfc/bin/${{ matrix.platform }}/*

  build-android:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64v8, x86_64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Android NDK
        uses: actions/setup-android@v4
        with:
          ndk-version: 25c

      - name: Install dependencies
        run: |
          python -m pip install scons

      - name: Build for Android (${{ matrix.arch }})
        run: |
          cd GDExtension
          scons platform=android target=template_release android_arch=${{ matrix.arch }} -j4
          mkdir -p ../addons/wfc/bin/android
          cp libwfc.* ../addons/wfc/bin/android/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-${{ matrix.arch }}
          path: addons/wfc/bin/android/*

  package-and-release:
    needs: [build, build-android]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          pattern: '*'
          merge-multiple: true

      - name: Prepare package
        run: |
          mkdir -p package/addons/wfc
          cp -r addons/wfc/* package/addons/wfc/
          cp LICENSE package/addons/wfc/
          
          # Organize binaries
          mkdir -p package/addons/wfc/bin/{windows,linux,macos,android}
          cp -r artifacts/windows/* package/addons/wfc/bin/windows/
          cp -r artifacts/linux/* package/addons/wfc/bin/linux/
          cp -r artifacts/macos/* package/addons/wfc/bin/macos/
          cp -r artifacts/android-*/* package/addons/wfc/bin/android/

      - name: Create ZIP
        run: |
          cd package
          zip -r ../wfc-plugin-${{ github.ref_name }}.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: wfc-plugin-${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}