name: Build and Package WFC Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform: [windows, linux]
      fail-fast: false
    runs-on: ${{ matrix.platform }}-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v5

      - name: Install SCons
        run: python -m pip install scons

      - name: Build Plugin
        shell: bash
        run: |
          # Crear directorio de salida primero
          mkdir -p GDExtension/addons/wfc/bin/${{ matrix.platform }}
          
          # Compilar
          cd GDExtension
          scons platform=${{ matrix.platform }} target=template_release -j4
          
          # Verificar archivos generados
          echo "=== Archivos generados en ${{ matrix.platform }} ==="
          if [ "${{ matrix.platform }}" == "windows" ]; then
            ls GDExtension/addons/wfc/bin/windows/
          else
            ls GDExtension/addons/wfc/bin/linux/
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}
          path: GDExtension/addons/wfc/bin/${{ matrix.platform }}/*

  package:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Package
        run: |
          mkdir -p package/addons/wfc
          cp -r GDExtension/addons/wfc/* package/addons/wfc/
          cp LICENSE package/addons/wfc/
          
          # Copiar binarios solo si existen
          [ -d artifacts/windows ] && cp -r artifacts/windows package/addons/wfc/bin/
          [ -d artifacts/linux ] && cp -r artifacts/linux package/addons/wfc/bin/

      - name: Create ZIP
        run: |
          cd package
          zip -r ../wfc-plugin-${{ github.ref_name }}.zip *

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          files: wfc-plugin-${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}