name: Build and Package WFC Plugin

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        platform: [windows, linux, macos, android]
        include:
          - platform: android
            arch: arm64v8
          - platform: android
            arch: x86_64

    runs-on: ${{ matrix.platform == 'android' && 'ubuntu-latest' || format('{0}-latest', matrix.platform) }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Android SDK
        if: matrix.platform == 'android'
        uses: android-actions/setup-android@v2
        with:
          ndk-version: 25c # Versión equivalente a r25c

      - name: Install dependencies
        run: |
          python -m pip install scons
          if [ "${{ matrix.platform }}" == "macos" ]; then
            brew install coreutils
          fi

      - name: Build for ${{ matrix.platform }}
        env:
          ANDROID_NDK_ROOT: ${{ github.workspace }}/android-ndk
        run: |
          cd GDExtension
          if [ "${{ matrix.platform }}" = "android" ]; then
            scons platform=android target=template_release android_arch=${{ matrix.arch }} -j4
            mkdir -p ../addons/wfc/bin/android
            cp libwfc.* ../addons/wfc/bin/android/
          else
            scons platform=${{ matrix.platform }} target=template_release -j4
            mkdir -p ../addons/wfc/bin/${{ matrix.platform }}
            cp libwfc.* ../addons/wfc/bin/${{ matrix.platform }}/
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }}-${{ matrix.arch || 'x86_64' }}
          path: |
            addons/wfc/bin/${{ matrix.platform }}/*

  package-and-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all binaries
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare package structure
        run: |
          mkdir -p package/addons/wfc
          cp -r addons/wfc/* package/addons/wfc/
          cp LICENSE package/addons/wfc/
          
          # Organize binaries
          mkdir -p package/addons/wfc/bin/{windows,linux,macos,android}
          find artifacts -name '*.dll' -exec cp {} package/addons/wfc/bin/windows/ \;
          find artifacts -name '*.so' -exec cp {} package/addons/wfc/bin/linux/ \;
          find artifacts -name '*.dylib' -exec cp {} package/addons/wfc/bin/macos/ \;
          find artifacts -name 'android-*' -exec cp -r {} package/addons/wfc/bin/android/ \;

      - name: Create ZIP archive
        run: |
          cd package
          zip -r ../wfc-plugin-${{ github.ref_name }}.zip *

      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            wfc-plugin-${{ github.ref_name }}.zip
          tag_name: ${{ github.ref_name }}
