name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Compile GDExtension for multiple platforms
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            platform: linux
            artifact_name: libwfc.linux.x86_64.so
            cores: $(nproc)
          - os: windows-latest
            platform: windows
            artifact_name: libwfc.windows.x86_64.dll
            cores: 2
          - os: macos-latest
            platform: macos
            artifact_name: libwfc.macos.x86_64.dylib
            cores: $(sysctl -n hw.logicalcpu)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install SCons (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt update && sudo apt install -y scons

      - name: Install SCons (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          choco install python --pre
          python -m pip install --upgrade pip
          pip install scons

      - name: Install SCons (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install scons

      - name: Build GDExtension
        run: cd GDExtension && scons platform=${{ matrix.platform }} target=template_release -j${{ matrix.cores }}

      - name: Upload built library
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: addons/wfc/bin/${{ matrix.platform }}/${{ matrix.artifact_name }}

  release:
    name: Package Release Files
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Download all compiled artifacts
        uses: actions/download-artifact@v4
  
      - name: Prepare release folder
        run: |
          mkdir -p release/addons/wfc/bin
          cp -r addons/wfc/demo release/addons/wfc/
          cp addons/wfc/plugin.cfg release/addons/wfc/
          cp addons/wfc/wfc_generator2d.gdextension release/addons/wfc/
          cp LICENSE release/addons/wfc/
  
          mkdir -p release/addons/wfc/bin/windows
          mkdir -p release/addons/wfc/bin/linux
          mkdir -p release/addons/wfc/bin/macos
  
          mv libwfc.windows.x86_64.dll release/addons/wfc/bin/windows/
          mv libwfc.linux.x86_64.so release/addons/wfc/bin/linux/
          mv libwfc.macos.x86_64.dylib release/addons/wfc/bin/macos/
  
      - name: Create ZIP archive
        run: |
          version=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
          zip -r "WaveFunctionCollapse-GodotAddon-${version}.zip" release/addons
  
      - name: Upload ZIP as artifact
        uses: actions/upload-artifact@v4
        with:
          name: WaveFunctionCollapse-GodotAddon
          path: WaveFunctionCollapse-GodotAddon-*.zip